SYSTEM:
  #平台名称 邮件文档等会用到
  SYS_TITLE: 'FastApi Naive'
  #平台链接 用于发送邮件等通知可能会用到 配置为前端地址
  SYS_LINK: 'https://localhost'
  #API文档描述
  SYS_DESCRIOTION: '
                    FastApi Naive Admin API 文档. 🚀


                    [GitHub](https://github.com/cary997/fastapi-naive-admin)
                    '
  #系统版本
  SYS_VERSION: 'v1.2.6'
  #router的前缀
  SYS_ROUTER_PREFIX: '/v1'
  #登录接口的url
  SYS_ROUTER_AUTH2: '/access-token'
  #刷新token接口的url
  SYS_ROUTER_REFRESH: '/refresh-token'
  #前端同步动态路由接口的url
  SYS_ROUTER_SYNCROUTES: '/async-routes'
  # 关闭api docs则更改为null
  SYS_OPENAPI_URL: '/openapi.json'

CORS:
  # 跨域配置
  CORS_ORIGINS: ["*"]
  CORS_ALLOW_CREDENTIALS: True
  CORS_ALLOW_METHODS: ["*"]
  CORS_ALLOW_HEADERS: ["*"]

LOG:
  # 日志路径
  LOG_PATH: 'logs/fastapi-naive.log'
  # 日志格式
  LOG_FORMAT: '<green>{time:YYYY-MM-DD HH:mm:ss:SSS}</green> | <level>{level}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>'
  # 日志级别
  LOG_LEVER: 'DEBUG'
  # 日志切割时间(每天)
  LOG_ROTATION_TIME: '00:00:00'
  # 日志切割大小
  LOG_ROTATION_SIZE: '500 MB'
  # 日志保留时间
  LOG_RETENTION: '15 days'
  # 是否输出控制台，False为不输出
  LOG_CONSOLE: True
  # 是否输出到文件，False为不输出
  LOG_FILE: False

SECURITY:
  # 密码加密KEY 16位数字和子母
  SECRET_KEY: 'TYK6tziA9azcb31d'
  SECRET_IV: 'FD2fnb7ytFatHeem'
  # JWT加密 openssl rand -hex 32
  SECRET_JWT_KEY: '26b38a12da2920855a9d839047525fa96f6fafc8a4c32379dd758e31022d33f3'
  SECRET_JWT_ALGORITHM: 'HS256'
  # JWT过期时间：分钟
  SECRET_JWT_EXP: 10
  # JWT刷新令牌过期时间：分钟
  SECRET_REJWT_EXP: 180

DATABASE:
  # 数据库类型,sqlite mysql postgres
  DB_ENGINE: 'sqlite'
  # (写)数据库连接地址：用户名:密码@Host:Port/dbname?...
  DB_WRITE_URL: 'root:root123@127.0.0.1:3306/fastapi?charset=utf8mb4'
  # (读)数据库连接地址：用户名:密码@Host:Port/dbname?...
  DB_RAER_URL: 'root:root123@127.0.0.1:3306/fastapi?charset=utf8mb4'
  #时区
  DB_TIMEZONE: 'Asia/Shanghai'

CACHE:
  # standalone cluster sentinel
  #REDIS_MODE: 'cluster'
  REDIS_MODE: 'standalone'
  # standalone模式选择使用的库
  REDIS_DB: 0
  # standalone：IP:Port，cluster和sentinel：IP1:Port1,IP2:Port2,...
  #REDIS_ADDRESS: '192.168.10.10:6380,192.168.10.10:6381,192.168.10.10:6382,192.168.10.10:6383,192.168.10.10:6384,192.168.10.10:6385'
  REDIS_ADDRESS: '127.0.0.1:6379'
  # Username,没有则null
  REDIS_USERNAME: null
  # Password
  REDIS_PASSWORD: null
  # sentinel name
  REDIS_SENTINEL_NAME: null
  # 编码
  REDIS_ENCODING: 'utf-8'
  # 最大连接数
  REDIS_MAX_CONNECTIONS: 50
  #是否开启SSL
  REDIS_SSL: False
  #SSl 强制执行主机名验证默认为：required
  REDIS_SSL_CERT_REQS: null
  #ssl ca证书路径/path/to/ca.pem
  REDIS_SSL_CA_CERTS: null